introppw/urls.py
from django.contrib import admin
from django.urls import path,include
from story_3 import views
# from polls import views
# from testform1 import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view),
    path('some/', views.some_view),
    path('oke/', views.oke_view),
    path('apa/', views.apa_view),
    path('course/', include('testform1.urls')),
    path('polls/' , include('polls.urls')),  
    path('event/' , include('story6.urls')), 
     # path('index/', views.index),
    # path('show/', views.show),
    # path('showAdmin/', views.showAdmin),
    # path('create/', views.create),
    # path('indexAdmin/', views.indexAdmin),

]

myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
	path('', views.hello),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name='index'),
    path('mudaKu/', views.mudaKu, name='mudaKu'),
    path('blueKu/', views.blueKu, name='blueKu'),
    path('time/', views.time, name='time'),
    path('time/<str:time>', views.time, name='time'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.indexEvent, name='indexEvent'),
    path('addEvent/', views.addEvent, name='addEvent'),
    path('addMember/<str:id>', views.addMember, name='addMember'),
    path('deleteMember/<str:id>', views.deleteMember, name='deleteMember')

]

story_3/urls.py
from django.urls import path
from . import views

app_name = ["story_3"]
urlpatterns = [
    path('', views.home_view, name="home_url"),
]

testform1/urls.py
from django.urls import path
from . import views

app_name = "matakuliah"


urlpatterns = [
    path('', views.index, name='index'),
    path('show/<str:order>/', views.show, name='show'),
    path('showAdmin/<str:order>/', views.showAdmin, name='showAdmin'),
    path('create', views.create, name='create'),
    path('indexAdmin', views.indexAdmin, name='indexAdmin'),
    path('indexAdmin/<str:order>/', views.indexAdmin, name='indexAdmin'),
]

myapp/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Member(models.Model):
    name = models.CharField(max_length=50)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

story_3/models.py
from django.db import models

# Create your models here.

testform1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MataKuliah(models.Model):
    order = models.AutoField(primary_key=True)
    namaMatkul = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    jumlahSKS = models.IntegerField()
    deskripsiMatkul = models.TextField()
    waktu = models.CharField(max_length=50)
    semester = models.CharField(max_length=100)

    def __str__(self):
        return self.namaMatkul
    
    def snippet(self):
        return self.deskripsiMatkul[0:150] + "..."

class Tugas(models.Model):
    namaTugas = models.CharField(max_length=100)
    tanggal = models.DateTimeField(auto_now=False, auto_now_add=False)
    deskripsiTugas = models.TextField()
    matakuliah = models.ForeignKey(MataKuliah, on_delete=models.CASCADE)

    def __str__(self):
        return self.namaTugas

story6/forms.py
from django import forms
from .models import Event, Member

class CreateEvent(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name']

class CreateMember(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name', 'event']

testform1/forms.py
from django import forms
from . import models

class CreateMatkul(forms.ModelForm):
    class Meta:
        model = models.MataKuliah
        fields = ['namaMatkul', 'dosen', 'jumlahSKS', 'deskripsiMatkul', 'waktu', 'semester']

myapp/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    	return render(request, 'hello.html')

polls/views.py
import datetime
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, "index.html", {'static' : 'true', 'color' : 'none'})
def mudaKu(request):
    color = 'muda'
    return render(request, "mudaKu.html", {'color' : color})
def blueKu(request):
    color = 'blue'
    return render(request, "blueKu.html", {'color' : color})
def time(request, time = '0'):
    time = int(time)
    time = time + 7
    TIME_ZONE = datetime.datetime.now() + datetime.timedelta(hours = time)
    return render(request, "time.html", {'time' : TIME_ZONE})

story6/views.py
from django.shortcuts import render, redirect
from .forms import CreateEvent, CreateMember
from .models import Event, Member

# Create your views here.
def indexEvent(request):
    event = Event.objects.all()
    member = Member.objects.all()
    return render(request, 'eventList.html', {'event' : event, "member" : member})

def addEvent(request):
    if request.method == 'POST':
        form = CreateEvent(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story6:indexEvent')
    return render(request, 'addEvent.html')

def addMember(request, id = 0):
    id = int(id)
    event = Event.objects.get(id=id)
    if request.method == 'POST':
        id = request.POST['eventId']
        name = request.POST['name']
        event = Event.objects.get(id=id)
        data = {'name' : name, 'event' : event}
        form = CreateMember(data=data)
        if form.is_valid():
            form.save()
            return redirect('story6:indexEvent')
    return render(request, 'addMember.html', {'event' : event})

def deleteMember(request, id):
    id = int(id)
    member = Member.objects.get(id=id)
    member.delete()
    return redirect('story6:indexEvent')

story_3/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
		return render(request, "home.html")
def some_view(request):
		return render(request, "blueKu.html")
def oke_view(request):
		return render(request, "mudaKu.html")
def apa_view(request):
		return render(request, "time.html")

testform1/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah, Tugas
from . import forms
import datetime

# Create your views here.
def index(request):
    matakuliah = MataKuliah.objects.all()
    return render(request, 'matkul.html', {'matakuliah' : matakuliah})

def show(request, order):
    order = int(order)
    matakuliah = MataKuliah.objects.get(order=order)
    tugas = Tugas.objects.filter(matakuliah=matakuliah)
    today = datetime.datetime.now().timestamp()
    masihLama = []
    besok = []
    udahLewat = []
    for item in tugas:
        if item.tanggal.timestamp() < today:
            udahLewat.append(item)
        elif item.tanggal.timestamp() < today + 86400:
            besok.append(item)
        else:
            masihLama.append(item)

    return render(request, "show.html", {"matakuliah" : matakuliah, "besok" : besok, "udahLewat" : udahLewat, "masihLama" : masihLama})

def showAdmin(request, order):
    order = int(order)
    matakuliah = MataKuliah.objects.get(order=order)
    return render(request, "showAdmin.html", {"matakuliah" : matakuliah})

def create(request):
    if (request.method == 'GET'):
        form = forms.CreateMatkul()
        return render(request, "create.html", {'form' : form})
    elif (request.method == 'POST'):
        form = forms.CreateMatkul(request.POST)
        if form.is_valid():
            form.save()
            return redirect('matakuliah:index')

def indexAdmin(request):
    if request.method == "POST":
        order = request.POST["order"]
        matakuliah = MataKuliah.objects.get(order=order)
        matakuliah.delete()
        return redirect('matakuliah:indexAdmin')
    else:
        matakuliah = MataKuliah.objects.all()
        return render(request, 'indexAdmin.html', {'matakuliah' : matakuliah})

myapp/templates/hello.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Bintang Portofolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
  </head>
  
  </head>
  <body>
    <div class="profile-img">
      <img src="{% static 'images/foto.jpg'%}" />
    </div>

    <div class="profile-info">
      <h1>Bintang Dominique</h1>
      <p class="about">
        <p>Hello world! Nama saya <b>Bintang Dominique</b> dari Ilmu Komputer 2019
        Universitas Indonesia. Saya biasa dipanggil Bintang. 
        <p> <b>NPM:</b> 1906292963.</p>
        <p> <b>Tempat,tanggal lahir :</b> Jakarta 19 November 2001</p>
        <p> <b>Alamat:</b> Taman Alfa Indah, Jakarta Barat</p>
        <p> <b>Telefon:</b> 082214014078</p>
        <p> <b>Email:</b> bintang.dominique@ui.ac.id</p>
        <p> <b>Hobi:</b> Travelling dan Olahraga</p>
        <p>Sedikit tentang saya, saya adalah anak yang senang bergaul dan berkomunikasi 
        dengan orang banyak.Saya memulai pendidikan saya dari taman kanak kanak. 
        <p>Saya memiliki akun line:@markasyours</p>
        <p>Saya tidak memiliki instagram.</p>
      
      <div class="social-media">
        <a href="https://www.instagram.com/kendalljenner/?hl=ens">
        <img src="{% static 'img/instagram.png'%}" /></a>
        <a href="http://line.me/ti/p/~markasyours">
        <img src="{% static 'img/line.png'%}" /></a>
      </div>

      <h2>Deskripsi singkat</h2>
      <div class="deskripsi">
         <!-- <img src="{% static 'img/monas.jpg'%}" />  -->
        <p><b>Tempat Kelahiranku</b></p>
        <small> Aku lahir di Jakarta dan sekarang tinggal di Jakarta. </small>
      </div>
      <div class="deskripsi">
         <!-- <img src="{% static 'img/ui.jpg'%}" />  -->
        <p><b>Universitas Ku</b></p>
        <small>
          Aku sekarang sedang menimba ilmu di Universitas Indonesia.
        </small>
      </div>
      <div class="deskripsi">
        <!-- <img src="{% static 'img/nasgor.jpg'%}" />  -->
        <p><b>Makanan Kesukaanku</b></p>
        <small>
          Aku sangat suka dengan makanan Indonesia terutama Nasi Goreng.
        </small>
      </div>
      <h2>Riwayat Pendidikan</h2>
      <p> SD Regina Pacis (2007-2013)</p>
      <p> SMP Regina Pacis (2013-2016)</p>
      <p> SMAN 63 Jakarta (2016-2019)</p>
      <p> Universitas Indonesia (2019-present)</p>
      <div class="belajar">
        <img src="{% static 'img/tka.jpg'%}" />
        <img src="{% static 'img/tk.jpg'%}" />
        <img src="{% static 'img/smp.jpg'%}" />
        <img src="{% static 'img/sma.jpg'%}" />
        <img src="{% static 'img/ui.jpg'%}" />
        <img src="{% static 'img/sd.jpg'%}" />
      </div>
      <div class="form-box">
        <h2>Hubungi Saya</h2>
        <form>
          <div class="input-group">
            <input type="text" placeholder="Nama Depan">
            <input type="text" placeholder="Nama Belakang">
          </div>
          <div class="input-group">
            <input type="number" placeholder="Telefon">
            <input type="email" placeholder="Email">
          </div>
          <div class="text-area">
            <textarea rows="4" placeholder="Pesan anda"></textarea>
          </div>
          <button type="submit" class="submit-btn">KIRIM PESAN</button>
        </form>
      </div>
    </div>
  </body>
</html>

polls/templates/blueKu.html
{% extends 'layout.html' %}
{% load static %}

{% block tittle %} Comming Soon {% endblock tittle %}
{% block content %} 
    <!-- section home -->
    <section class="muda-Ku blue">
        <h1 class="text-white home-tittle">Stay Tune..</h1>
    </section>
    <!-- endsection -->
{% endblock content %}

polls/templates/mudaKu.html
{% extends 'layout.html' %}
{% load static %}

{% block tittle %} ComingSoon {% endblock tittle %}
{% block content %}
    <!-- section home -->
    <section class="muda-Ku">
        <h1 class="text-white home-tittle">Stay Tune..</h1>
    </section>
    <!-- endsection -->
{% endblock content %}

polls/templates/time.html
{% extends 'layout.html' %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'style/time.css' %}">
{% endblock css %}

{% block tittle %} Home Page {% endblock tittle %}

{% block content %} 
<div class="timeContainer">
    <span>{{time}}</span>
</div>
{% endblock content %}

story6/templates/addEvent.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/course.css' %}">
{% endblock css %}

{% block tittle %}Add Event{% endblock tittle %}

{% block content %}
<div class="courses xlSize">
    <div class="header"><h1>Add Event</h1></div>
    <form action="" method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Nama Event</label>
            <input type="text" class="form-control" name="name" id="name" aria-describedby="eventNameHelp">
            <small id="eventNameHelp" class="form-text text-muted">Tell us about your event</small>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
    
{% endblock content %}

story6/templates/addMember.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/course.css' %}">
{% endblock css %}

{% block tittle %}Add Event{% endblock tittle %}

{% block content %}
<div class="courses xlSize">
    <div class="header"><h1>Add Member</h1></div>
    <form action="" method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name </label>
            <span>Event : {{event.name}}</span>
            <input type="text" class="form-control" name="name" id="name" aria-describedby="eventNameHelp">
            <input type="hidden" name="eventId" value="{{event.id}}">
            <small id="eventNameHelp" class="form-text text-muted">Tell us your New Member</small>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
    
{% endblock content %}

story6/templates/eventList.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/course.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock css %}

{% block tittle %}Event List{% endblock tittle %}

{% block content %}
<div class="courses">
    <div class="header"><h1>Event</h1></div>
    <button type="button" class="btn btn-primary btn-lg my-2" onclick="location.href='{% url 'story6:addEvent' %}'">Add Event</button>
    {% if event is not none %}
        <div class="table">
            {% for i in event %}
            <div class="card">
                <h5 class="card-header">{{ i.name }}</h5>
                <div class="card-body">
                <h5 class="card-title">Member :</h5>
                <ul class="list-group">
                {% for j in member %}
                    {% if j.event == i %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>{{j.name}}</span>
                            <a class="material-icons text-danger text-decoration-none" href="{% url 'story6:deleteMember' j.id %}">delete_outline</a>
                        </li>
                    {% endif %}
                {% endfor %}
                </ul>
                <button type="button" class="btn btn-info my-2" onclick="location.href='{% url 'story6:addMember' id=i.id %}'">Add Member</button>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h1>Event Not Exist</h1>
    {% endif %}
</div>
    
{% endblock content %}

story_3/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    {% block css %}

    {% endblock css %}
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:800|Roboto&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'img/favicon.png'%}">
    <title>{% block tittle %}{% endblock tittle %}</title>
</head>
<body>
        <!-- navbar section -->
        <div class="navbarku {% if color == 'muda' %} muda {% elif color == 'blue'%} blue {% endif %}" id="navbar">
            <div class="logo"><a href="" {% if color == 'muda' or color == 'blue' %} class="text-white" {% endif %}>Hello.</a></div>
            <div class="mobile-menu-button" id="mobile-menu-button" onclick="tooglebtn1()">
                <span {% if color == 'muda' or color == 'blue' %} class="white" {% endif%}></span>
                <span {% if color == 'muda' or color == 'blue' %} class="white" {% endif %}></span>
                <span {% if color == 'muda' or color == 'blue' %} class="white" {% endif%}></span>
            </div>
            <div class="selection">
                {% if color == 'none' %}
                <ul>
                    <li><a href="{% url 'polls:index' %}" class="nav-select">Home</a><span class="active"></span></li>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="#about" class="nav-select">About</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="#expertise" class="nav-select">Expertise</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select">Course</a><span class="nav-line"></span></li> 
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select">Contact</a><span class="nav-line"></span></li>
                </ul>
                {% elif color == 'muda' %}
                <ul>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="{% url 'polls:index' %}" class="nav-select text-white">Home</a><span class="nav-line white"></span></li>
                    <li><a href="" class="nav-select text-white">About</a><span class="active white"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:blueKu' %}" class="nav-select text-white">Expertise</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select text-white">Course</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select text-white">Contact</a><span class="nav-line white"></span></li>
                </ul>
                {% elif color == 'blue'%}
                <ul>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="{% url 'polls:index' %}" class="nav-select text-white">Home</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:mudaKu' %}" class="nav-select text-white">About</a><span class="nav-line white"></span></li>
                    <li><a href="" class="nav-select text-white">Expertise</a><span class="active white"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select text-white">Course</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select text-white">Contact</a><span class="nav-line white"></span></li>
                </ul>
                {% else %}
                <ul>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="{% url 'polls:index' %}" class="nav-select">Home</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:mudaKu' %}" class="nav-select">About</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:blueKu' %}" class="nav-select">Expertise</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select">Course</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select">Contact</a><span class="nav-line"></span></li>
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="big-nav {% if color == 'muda' %} muda {% elif color == 'blue'%} blue {% endif %}" id="select">
            {% if color == 'muda' or color == 'blue' %}
            <div class="selection" onclick="tooglebtn1()" >
                <a href="{% url 'polls:index' %}" class="text-white">Home</a>
                <a href="{% url 'polls:mudaKu' %}" class="text-white">About</a>
                <a href="{% url 'matakuliah:index' %}" class="text-white">Course</a> 
                <a href="{% url 'polls:blueKu' %}" class="text-white">Expertise</a>
                <a href="#contact" class="text-white">Contact</a>
            </div>
            {% else %}
            <div class="selection" onclick="tooglebtn1()" >
                <a href="{% url 'polls:index' %}">Home</a>
                <a href="{% url 'polls:mudaKu' %}">About</a>
                <a href="{% url 'matakuliah:index' %}">Course</a> 
                <a href="{% url 'polls:blueKu' %}">Expertise</a>
                <a href="#contact">Contact</a>
            </div>
            {% endif %}
        </div>
        <!-- endsection -->
        {% block content %}

        {% endblock content %}
        <!-- section footer -->
        <section class="footer" id="contact">
      <div class="email">
        <span
          >Email --
          <a
            href="https://mail.google.com/mail/?to=inbox@example.com&bcc=admin@example.com&subject=Hey#compose"
            >bintangdom19@gmail.com</a
          ></span
        >
      </div>
      <div class="socmed">
        <!-- {% static 'foto.jpg' %} -->
        <a href="https://www.linkedin.com/in/bintang-dominique-ba0667196/"
          ><img src="{% static 'img/linkedin.png' %}" alt=""
        /></a>
        <a
          href="https://twitter.com/KendallJenner?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"
          ><img src="{% static 'img/twitter.png' %}" alt=""
        /></a>
        <a href="http://line.me/ti/p/markasyours"
          ><img src="{% static 'img/line.png' %}" alt=""
        /></a>
        <a href="https://api.whatsapp.com/send?phone=6282214014078"
          ><img src="{% static 'img/whatsap.png' %} " alt=""
        /></a>
        <a href="https://www.instagram.com/kendalljenner/?hl=en"
          ><img src="{% static 'img/instagram.png' %}" alt=""
        /></a>
      </div>
    </section>
        <!-- endsection -->
</body>

{% block js %} 

{% endblock js %}
<script src="{% static 'style/navbar.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

story_3/templates/time.html
{% extends 'layout.html' %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'style/time.css' %}">
{% endblock css %}

{% block tittle %} Home Page {% endblock tittle %}

{% block content %} 
<div class="timeContainer">
    <span>{{time}}</span>
</div>
{% endblock content %}

testform1/templates/create.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/course.css' %}">
{% endblock css %}

{% block tittle %} Courses {% endblock tittle %}

{% block content %}
<div class="form-model">
    {% load crispy_forms_tags %}
    <form action="" method="post" class="">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

testform1/templates/indexAdmin.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/course.css' %}">
{% endblock css %}

{% block tittle %} Courses {% endblock tittle %}

{% block content %}
<div class="courses">
    <div class="header"><h1>Courses</h1></div>
    {% if matakuliah is not none %}
        <div class="table">
            {% for i in matakuliah %}
            <div class="card">
                <h5 class="card-header">{{ i.namaMatkul }}</h5>
                <div class="card-body">
                <h5 class="card-title">Jumlah SKS = {{i.jumlahSKS}}</h5>
                <p class="card-text">{{i.snippet}}</p>
                <a href="{% url 'matakuliah:showAdmin' order=i.order %}" class="btn btn-primary">Detail</a>
                <form action="" method="POST" class="delete-btn">
                    {% csrf_token %}
                    <input type="hidden" name="order" value="{{i.order}}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </div>
            </div>
            {% endfor %}
            <button type="button" class="btn btn-info" onclick="location.href='{% url 'matakuliah:create' %}'">Add Data</button>
        </div>
    {% else %}
    <h1>Courses Not Exist</h1>
    {% endif %}
</div>
    
{% endblock content %}

testform1/templates/matkul.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/course.css' %}">
{% endblock css %}

{% block tittle %} Courses {% endblock tittle %}

{% block content %}
<div class="courses">
    <div class="header"><h1>Courses</h1></div>
    {% if matakuliah is not none %}
        <div class="table">
            {% for i in matakuliah %}
            <div class="card">
                <h5 class="card-header">{{ i.namaMatkul }}</h5>
                <div class="card-body">
                <h5 class="card-title">Jumlah SKS = {{i.jumlahSKS}}</h5>
                <p class="card-text">{{i.snippet}}</p>
                <a href="{% url 'matakuliah:show' order=i.order %}" class="btn btn-primary">Detail</a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h1>Courses Not Exist</h1>
    {% endif %}
</div>
    
{% endblock content %}